// Pre-processed data for the A1 Spanish Quiz App
const themesData = [
    {
        id: "food",
        nameFr: "Nourriture / boissons / restaurant",
        nameEs: "Alimentación y Restaurante",
        icon: "🍴",
        color: "#FF6B6B",
        questions: [
            { q: "pomme", a: "manzana", m: "Imagine une pomme qui chante 'manzana' en dansant.", cat: "Fruits" },
            { q: "poire", a: "pera", m: "Pense à 'Père Noël' qui mange une 'pera' à Noël.", cat: "Fruits" },
            { q: "pêche", a: "melocotón", m: "'Melocotón' contient 'melo' comme dans 'melodie' : une pêche mélodieuse.", cat: "Fruits" },
            { q: "orange", a: "naranja", m: "'Naranja' rime avec 'orange' et contient 'naran' comme 'narrateur' : une orange qui raconte des histoires.", cat: "Fruits" },
            { q: "pastèque", a: "sandía", m: "'Sandía' contient 'sand' comme 'sable' : une pastèque sur la plage.", cat: "Fruits" },
            { q: "mûre", a: "mora", m: "'Mora' ressemble à 'mure' en français, imagine une muraille de mûres.", cat: "Fruits" },
            { q: "fraise", a: "fresa", m: "'Fresa' ressemble à 'fraise' et contient 'fres' comme 'frais'.", cat: "Fruits" },
            { q: "cerise", a: "cereza", m: "'Cereza' contient 'cere' comme dans 'céréale'.", cat: "Fruits" },
            { q: "citron", a: "limón", m: "'Limón' ressemble à 'limonade', qui est faite avec du citron.", cat: "Fruits" },
            { q: "melon", a: "melón", m: "Le mot est presque identique en français et en espagnol.", cat: "Fruits" },
            { q: "myrtille", a: "arándano", m: "'Arándano' contient 'rano' comme dans 'grenouille' (rana), imagine une grenouille bleue qui mange des myrtilles.", cat: "Fruits" },
            { q: "raisin", a: "uva", m: "'Uva' est court et facile : imagine une grappe de raisin en forme de 'U'.", cat: "Fruits" },
            { q: "ananas", a: "piña", m: "'Piña' ressemble à 'pine', comme l'ananas qui a des feuilles pointues comme un pin.", cat: "Fruits" },
            { q: "banane", a: "plátano", m: "'Plátano' contient 'plat' : imagine une banane plate.", cat: "Fruits" },
            { q: "mangue", a: "mango", m: "Le mot est identique en français et en espagnol.", cat: "Fruits" },
            { q: "kiwi", a: "kiwi", m: "Le mot est identique en français et en espagnol.", cat: "Fruits" },
            { q: "avocat", a: "aguacate", m: "'Aguacate' contient 'agua' (eau) et 'cate' comme dans 'catapulte' : un avocat qui catapulte de l'eau.", cat: "Fruits" },
            { q: "prune", a: "ciruela", m: "'Ciruela' contient 'cir' comme dans 'cirque' : une prune qui fait le cirque.", cat: "Fruits" },
            { q: "pain", a: "pan", m: "'Pan' est très proche du mot français, imagine un panier à pain.", cat: "Boulangerie" },
            { q: "vin", a: "vino", m: "'Vino' ressemble à 'vin ô' : un vin qui dit 'oh'.", cat: "Boissons" },
            { q: "soupe", a: "sopa", m: "'Sopa' ressemble à 'soupe' et contient 'opa' comme dans 'opéra' : une soupe qui chante à l'opéra.", cat: "Plats" },
            { q: "thé", a: "té", m: "Le mot est identique en français et en espagnol.", cat: "Boissons" },
            { q: "sandwich", a: "sándwich", m: "Le mot est presque identique en français et en espagnol.", cat: "Plats" },
            { q: "eau", a: "agua", m: "'Agua' ressemble à 'eau' et commence par 'a' comme 'aquatique'.", cat: "Boissons" },
            { q: "saumon", a: "salmón", m: "'Salmón' contient 'sal' comme dans 'saleté' : un saumon qui nage dans la mer salée.", cat: "Poisson" },
            { q: "salade", a: "ensalada", m: "'Ensalada' contient 'salade' : pense à 'en salade'.", cat: "Plats" },
            { q: "poulet", a: "pollo", m: "'Pollo' ressemble à 'poulet' et contient 'polo', comme un poulet qui joue au polo.", cat: "Viande" },
            { q: "bœuf", a: "carne", m: "'Carne' signifie 'viande' en général, pense à 'carnivore'.", cat: "Viande" },
            { q: "noix", a: "nuez", m: "'Nuez' ressemble à 'nœud' : une noix qui fait un nœud dans un arbre.", cat: "Encas" },
            { q: "cacahuète", a: "cacahuete", m: "Le mot est identique en français et en espagnol.", cat: "Encas" },
            { q: "amande", a: "almendra", m: "'Almendra' contient 'amande' et 'al' comme dans 'allumette' : une amande en forme d'allumette.", cat: "Encas" },
            { q: "chou", a: "repollo", m: "'Repollo' contient 'pollo' comme 'poulet' : un chou qui ressemble à un poulet.", cat: "Légumes" },
            { q: "maïs", a: "maíz", m: "'Maíz' contient 'maïs' et se termine par 'z' comme 'zèbre' : un champ de maïs avec des zèbres.", cat: "Légumes" },
            { q: "haricot", a: "frijol", m: "'Frijol' contient 'fri' comme dans 'frit' : un haricot frit.", cat: "Légumes" },
            { q: "pois", a: "guisante", m: "'Guisante' contient 'guise' comme dans 'déguisement' : un pois déguisé.", cat: "Légumes" },
            { q: "brocoli", a: "brócoli", m: "Le mot est presque identique en français et en espagnol.", cat: "Légumes" },
            { q: "carotte", a: "zanahoria", m: "'Zanahoria' contient 'zani' comme dans 'zany' (farfelu) : une carotte farfelue.", cat: "Légumes" },
            { q: "poivron", a: "pimiento", m: "'Pimiento' contient 'piment' : un poivron qui pimente.", cat: "Légumes" },
            { q: "piment", a: "chile", m: "'Chile' comme le pays, imagine un piment en forme de Chili.", cat: "Légumes" },
            { q: "citrouille", a: "calabaza", m: "'Calabaza' contient 'cal' comme dans 'calcul' : une citrouille qui calcule.", cat: "Légumes" },
            { q: "aubergine", a: "berenjena", m: "'Berenjena' contient 'bère' comme dans 'berceuse' : une aubergine qui berce.", cat: "Légumes" },
            { q: "oignon", a: "cebolla", m: "'Cebolla' contient 'bola' (balle) : un oignon en forme de balle.", cat: "Légumes" },
            { q: "ail", a: "ajo", m: "'Ajo' est court et facile, pense à 'ail ô' : un ail qui dit 'oh'.", cat: "Légumes" },
            { q: "dinde", a: "pavo", m: "'Pavo' ressemble à 'pava' comme dans 'pavane' : une dinde qui danse la pavane.", cat: "Viande" },
            { q: "riz", a: "arroz", m: "'Arroz' contient 'roz' comme dans 'rose' : du riz en forme de roses.", cat: "Plats" },
            { q: "steak", a: "filete", m: "'Filete' contient 'filet' : un steak en filet.", cat: "Viande" },
            { q: "crevette", a: "gamba", m: "'Gamba' ressemble à 'jambe' : une crevette avec des jambes.", cat: "Poisson" },
            { q: "fromage", a: "queso", m: "'Queso' ressemble à 'késako' : un fromage mystérieux.", cat: "Produits laitiers" },
            { q: "œuf", a: "huevo", m: "'Huevo' commence par 'hue', comme 'huer' (crier) : un œuf qui crie.", cat: "Base" },
            { q: "pâtes", a: "pasta", m: "Le mot est presque identique en français et en espagnol.", cat: "Plats" },
            { q: "pizza", a: "pizza", m: "Le mot est identique en français et en espagnol.", cat: "Plats" },
            { q: "hamburger", a: "hamburguesa", m: "'Hamburguesa' contient 'hamburger' : facile à retenir.", cat: "Plats" },
            { q: "hot-dog", a: "perro caliente", m: "'Perro caliente' signifie 'chien chaud' : un hot-dog en forme de chien.", cat: "Plats" },
            { q: "café", a: "café", m: "Le mot est identique en français et en espagnol.", cat: "Boissons" },
            { q: "bière", a: "cerveza", m: "'Cerveza' contient 'cerve' comme dans 'cerveau' : une bière qui donne des idées.", cat: "Boissons" },
            { q: "champagne", a: "champán", m: "'Champán' ressemble à 'champagne' et se termine par 'án' comme 'année' : du champagne pour la nouvelle année.", cat: "Boissons" },
            { q: "soda", a: "refresco", m: "'Refresco' contient 'frais' : un soda rafraîchissant.", cat: "Boissons" }
        ]
    },
    {
        id: "city",
        nameFr: "Ville / maison / lieux / transport",
        nameEs: "Ciudad, Casa y Transporte",
        icon: "🏙️",
        color: "#4D96FF",
        questions: [
            { q: "la ville", a: "la ciudad", m: "Pense à 'city' en anglais, qui ressemble à 'ciudad'.", cat: "Ville" },
            { q: "la rue", a: "la calle", m: "Imagine-toi en train de 'caller' (appeler) quelqu’un dans la rue.", cat: "Ville" },
            { q: "la place", a: "la plaza", m: "Pense à la 'Piazza' en italien, qui ressemble à 'plaza'.", cat: "Ville" },
            { q: "le parc", a: "el parque", m: "Le mot 'parque' ressemble au français 'parc'.", cat: "Lieux" },
            { q: "le magasin", a: "la tienda", m: "Pense à 'tente' : une boutique peut ressembler à une tente sur un marché.", cat: "Commerce" },
            { q: "le restaurant", a: "el restaurante", m: "Le mot se termine comme 'restaurant' en français.", cat: "Commerce" },
            { q: "la maison", a: "la casa", m: "Pense à la 'casa' de 'casanova'.", cat: "Habitation" },
            { q: "l’école", a: "la escuela", m: "Le mot contient 'cole', comme 'collège' en français.", cat: "Lieux" },
            { q: "l’hôpital", a: "el hospital", m: "Le mot ressemble à 'hospital' en anglais.", cat: "Santé" },
            { q: "le musée", a: "el museo", m: "Le mot est presque identique au français 'musée'.", cat: "Loisirs" },
            { q: "le cinéma", a: "el cine", m: "Pense à 'cinéma' sans le 'ma' final.", cat: "Loisirs" },
            { q: "la banque", a: "el banco", m: "Pense à 'banque' et à 'banc' (siège), car on peut s’asseoir devant une banque.", cat: "Lieux" },
            { q: "la gare", a: "la estación", m: "Pense à 'station' en français, car une gare est une station de train.", cat: "Transport" },
            { q: "le métro", a: "el metro", m: "Le mot est identique en français et en espagnol.", cat: "Transport" },
            { q: "le bus", a: "el autobús", m: "Pense à 'auto' (voiture) et 'bus'.", cat: "Transport" },
            { q: "le taxi", a: "el taxi", m: "Le mot est identique en français et en espagnol.", cat: "Transport" },
            { q: "la voiture", a: "el coche", m: "Pense à 'cocher' : on peut cocher une case pour réserver une voiture.", cat: "Transport" },
            { q: "le vélo", a: "la bicicleta", m: "Pense à 'bicyclette' en français.", cat: "Transport" },
            { q: "le salon", a: "el salón", m: "Pensez à un salon élégant où l'on reçoit les invités.", cat: "Maison" },
            { q: "la cuisine", a: "la cocina", m: "Imaginez-vous en train de cuisiner des plats délicieux.", cat: "Maison" },
            { q: "la chambre", a: "el dormitorio", m: "C'est là où l'on dort, 'dormitorio' vient de dormir.", cat: "Maison" },
            { q: "le lit", a: "la cama", m: "C'est là où l'on dort, comme en français.", cat: "Mobilier" },
            { q: "le canapé", a: "el sofá", m: "Le mot est identique au français.", cat: "Mobilier" },
            { q: "la table", a: "la mesa", m: "Imagine une 'mesa' (table) où tu manges des 'maïs' (mesa/maïs).", cat: "Mobilier" },
            { q: "le meuble", a: "el mueble", m: "'Mueble' ressemble à 'meuble', et les deux commencent par 'm'.", cat: "Mobilier" },
            { q: "les chaises", a: "las sillas", m: "Pense à 'sillas' comme à des chaises qui 'sifflent' quand on les déplace.", cat: "Mobilier" },
            { q: "les coussins", a: "los cojines", m: "'Cojines' sonne comme 'coquin' : des coussins coquins pour se détendre !", cat: "Mobilier" },
            { q: "l'armoire", a: "el armario", m: "'Armario' contient 'armé' : ton armoire est armée contre le désordre !", cat: "Mobilier" },
            { q: "la lampe", a: "la lámpara", m: "'Lámpara' ressemble à 'lampe' et contient 'lamp' en anglais.", cat: "Mobilier" },
            { q: "le garage", a: "el garaje", m: "'Garaje' ressemble à 'garage' en français, avec un 'j' à la place du 'g' final.", cat: "Maison" },
            { q: "la bibliothèque", a: "la biblioteca", m: "'Biblioteca' contient 'bibli' comme 'bibliothèque'.", cat: "Lieux" },
            { q: "la buanderie", a: "el lavadero", m: "'Lavadero' vient de 'laver' : c’est là où on lave le linge.", cat: "Maison" },
            { q: "la salle de bains", a: "el baño", m: "'Baño' ressemble à 'bain' en français.", cat: "Maison" },
            { q: "la terrasse", a: "la terraza", m: "'Terraza' contient 'terre' : une terrasse est souvent en plein air, sur la terre.", cat: "Maison" },
            { q: "le jardin", a: "el jardín", m: "'Jardín' ressemble à 'jardin' en français, avec un accent sur le 'i'.", cat: "Maison" },
            { q: "la salle à manger", a: "el comedor", m: "'Comedor' vient de 'comer' (manger) : c’est là où on mange !", cat: "Maison" },
            { q: "les maisons mitoyennes", a: "las casas adosadas", m: "'Adosadas' vient de 'adossées' : des maisons collées l’une à l’autre.", cat: "Habitation" },
            { q: "le palace", a: "el palacio", m: "'Palacio' ressemble à 'palace' en français.", cat: "Habitation" },
            { q: "l'appartement", a: "el apartamento", m: "'Apartamento' ressemble à 'appartement', avec un 'o' à la fin.", cat: "Habitation" },
            { q: "le grenier / l'attique", a: "el ático", m: "'Ático' sonne comme 'attique' : c’est tout en haut de l’immeuble.", cat: "Maison" },
            { q: "la maison de campagne", a: "la casa de campo", m: "'Casa de campo' signifie littéralement 'maison des champs'.", cat: "Habitation" },
            { q: "la villa", a: "la villa", m: "Le mot est identique en français et en espagnol !", cat: "Habitation" }
        ]
    },
    {
        id: "activities",
        nameFr: "Activités / sports",
        nameEs: "Actividades y Deportes",
        icon: "⚽",
        color: "#6BCB77",
        questions: [
            { q: "courir", a: "correr", m: "'Correr' et 'courir' commencent tous les deux par 'cor-'.", cat: "Verbes" },
            { q: "marcher", a: "caminar", m: "'Caminar' et 'marcher' ont tous deux un 'm' et un 'r'.", cat: "Verbes" },
            { q: "écrire", a: "escribir", m: "'Escribir' et 'écrire' commencent par un 'e'.", cat: "Verbes" },
            { q: "boire", a: "beber", m: "'Beber' et 'boire' commencent tous deux par un 'b'.", cat: "Verbes" },
            { q: "travailler", a: "trabajar", m: "'Trabajar' et 'travailler' commencent par 'tra-'.", cat: "Verbes" },
            { q: "lire", a: "leer", m: "'Leer' et 'lire' commencent tous deux par un 'l'.", cat: "Verbes" },
            { q: "manger", a: "comer", m: "L'action de se nourrir.", cat: "Verbes" },
            { q: "natation", a: "natación", m: "Ressemble au français 'natation'.", cat: "Sports" },
            { q: "escrime", a: "esgrima", m: "L'arme s'appelle un 'escrime'.", cat: "Sports" },
            { q: "basket-ball", a: "baloncesto", m: "Pensez au 'ballon' dans le 'cesto' (panier).", cat: "Sports" },
            { q: "tennis", a: "tenis", m: "Presque identique.", cat: "Sports" },
            { q: "athlétisme", a: "atletismo", m: "Très proche du français.", cat: "Sports" },
            { q: "boxe", a: "boxeo", m: "Ajoutez un 'o' à boxe.", cat: "Sports" },
            { q: "football", a: "fútbol", m: "L'accent est sur le 'ú'.", cat: "Sports" },
            { q: "nager", a: "nadar", m: "Nageur, nager, nadar.", cat: "Verbes" },
            { q: "danser", a: "bailar", m: "Bailar, comme un bal.", cat: "Verbes" },
            { q: "chanter", a: "cantar", m: "Comme une cantate.", cat: "Verbes" },
            { q: "Le judo", a: "el judo", m: "Pense à 'judo' qui se prononce presque pareil en français et en espagnol, seul l'article change : 'el' au lieu de 'le'.", cat: "Sports" },
            { q: "Le handball", a: "el balonmano", m: "'Balón' (ballon) + 'mano' (main) = 'balonmano'. Imagine un ballon dans la main !", cat: "Sports" },
            { q: "La course à pied", a: "correr / el atletismo", m: "'Correr' ressemble à 'courir'. Pour 'atletismo', pense à 'athlétisme' en français.", cat: "Sports" },
            { q: "Le golf", a: "el golf", m: "C'est un mot international, il reste identique en espagnol.", cat: "Sports" },
            { q: "Le ski", a: "el esquí", m: "Pense à 'esquiver' en français, qui a une sonorité proche.", cat: "Sports" },
            { q: "Le surf", a: "el surf", m: "Un autre mot international, il ne change pas en espagnol.", cat: "Sports" },
            { q: "Le bowling", a: "los bolos / el bóling", m: "'Bolos' ressemble à 'boules', et 'bóling' est proche de 'bowling'.", cat: "Sports" },
            { q: "Peindre", a: "pintar", m: "Pense à 'peinture' en français, qui commence par 'peint-' comme 'pintar'.", cat: "Loisirs" },
            { q: "Arroser les plantes", a: "regar las plantas", m: "'Regar' ressemble à 'arroser' et 'plantas' à 'plantes'.", cat: "Loisirs" },
            { q: "Jouer aux jeux vidéo", a: "jugar a los videojuegos", m: "'Jugar' signifie 'jouer', et 'videojuegos' est très proche de 'jeux vidéo'.", cat: "Loisirs" },
            { q: "Jouer de la guitare", a: "tocar la guitarra", m: "'Tocar' signifie 'toucher' ou 'jouer d'un instrument', et 'guitarra' est presque identique à 'guitare'.", cat: "Loisirs" }
        ]
    },
    {
        id: "environment",
        nameFr: "L'environnement / planète",
        nameEs: "Medio Ambiente y Planeta",
        icon: "🌍",
        color: "#47B5FF",
        questions: [
            { q: "environnement", a: "medio ambiente", m: "Imaginez un 'médium' qui parle de l'environnement.", cat: "Général" },
            { q: "recyclage", a: "reciclaje", m: "Pensez à 'cycle' dans 'reciclaje'.", cat: "Action" },
            { q: "énergie solaire", a: "energía solar", m: "Pensez au soleil (sol).", cat: "Énergie" },
            { q: "déforestation", a: "deforestación", m: "Pensez à 'forêt'.", cat: "Problèmes" },
            { q: "pollution", a: "contaminación", m: "Imaginez un conteneur contaminé.", cat: "Problèmes" },
            { q: "planète", a: "planeta", m: "Très proche du français.", cat: "Général" },
            { q: "nature", a: "naturaleza", m: "C'est la nature.", cat: "Général" },
            { q: "réchauffement climatique", a: "calentamiento global", m: "Calentamiento vient de 'caliente' (chaud).", cat: "Problèmes" }
        ]
    },
    {
        id: "health",
        nameFr: "La santé / corps humains",
        nameEs: "Salud y Cuerpo Humano",
        icon: "🏥",
        color: "#D67BFF",
        questions: [
            { q: "tête", a: "cabeza", m: "Pensez à 'caboche'.", cat: "Corps" },
            { q: "bras", a: "brazo", m: "Ressemble au bras.", cat: "Corps" },
            { q: "main", a: "mano", m: "Une manœuvre se fait à la main.", cat: "Corps" },
            { q: "jambe", a: "pierna", m: "On se tient sur ses jambes.", cat: "Corps" },
            { q: "pied", a: "pie", m: "Un pied.", cat: "Corps" },
            { q: "œil", a: "ojo", m: "Les yeux sont le miroir de l'âme.", cat: "Corps" },
            { q: "nez", a: "nariz", m: "Les narines.", cat: "Corps" },
            { q: "bouche", a: "boca", m: "La bouche.", cat: "Corps" },
            { q: "malade", a: "enfermo", m: "Enfermo ressemble à l'enfer.", cat: "Santé" },
            { q: "médecin", a: "médico", m: "On y ajoute un 'o'.", cat: "Santé" },
            { q: "pharmacie", a: "farmacia", m: "Ressemble à farmacia.", cat: "Santé" },
            { q: "hôpital", a: "hospital", m: "Identique sans l'accent.", cat: "Santé" },
            { q: "le pansement", a: "la tirita / el esparadrapo", m: "Pense à 'tira' comme dans 'tirer' : quand tu tires sur un pansement, ça fait mal !", cat: "Santé" },
            { q: "la pilule", a: "la pastilla", m: "Associe 'pastilla' à 'pastille' en français, car une pilule ressemble à une petite pastille.", cat: "Santé" },
            { q: "le médicament", a: "el medicamento", m: "Le mot ressemble beaucoup au français : 'médicament' → 'medicamento'.", cat: "Santé" },
            { q: "la piqûre", a: "la inyección", m: "'Inyección' contient 'injection', comme quand on te fait une piqûre, on t’injecte quelque chose.", cat: "Santé" },
            { q: "le masque", a: "la mascarilla", m: "Pense à 'mascara' (masque en anglais) et ajoute '-illa' pour le rendre plus espagnol.", cat: "Santé" },
            { q: "le gel hydroalcoolique", a: "el gel hidroalcohólico", m: "Le mot est presque identique au français, avec 'hidro-' pour 'hydro-' et 'alcohólico' pour 'alcoolique'.", cat: "Santé" }
        ]
    },
    {
        id: "verbs",
        nameFr: "Verbes (Texte à trous / Flashcards)",
        nameEs: "Verbos y Gramática",
        icon: "📝",
        color: "#FFA41B",
        questions: [
            { q: "être", a: "ser / estar", m: "SER pour les caractéristiques permanentes, ESTAR pour les états temporaires.", cat: "Auxiliaires" },
            { q: "avoir", a: "tener", m: "Imagine un 'tennis' : tu 'tiens' ta raquette.", cat: "Auxiliaires" },
            { q: "faire", a: "hacer", m: "'Hacer' ressemble à 'hache'.", cat: "Actions" },
            { q: "aller", a: "ir", m: "Ira (colère) : tu vas partir.", cat: "Déplacement" },
            { q: "dire", a: "decir", m: "Ressemble à dire.", cat: "Communication" },
            { q: "pouvoir", a: "poder", m: "Pense à un pote qui peut.", cat: "Capacité" },
            { q: "devoir", a: "deber", m: "Ressemble à devoir.", cat: "Obligation" },
            { q: "vouloir", a: "querer", m: "Vouloir avec le cœur.", cat: "Désir" },
            { q: "savoir", a: "saber", m: "Saveur du savoir.", cat: "Connaissance" },
            { q: "venir", a: "venir", m: "Identique.", cat: "Déplacement" },
            { q: "voir", a: "ver", m: "Voir la couleur verte.", cat: "Perception" },
            { q: "donner", a: "dar", m: "Un don.", cat: "Actions" },
            { q: "prendre", a: "tomar", m: "Prendre une tomate.", cat: "Actions" },
            { q: "mettre", a: "poner", m: "Poser.", cat: "Actions" },
            { q: "partir / sortir", a: "salir", m: "Sortir de chez soi.", cat: "Déplacement" },
            { q: "connaître", a: "conocer", m: "Etre avec quelqu'un.", cat: "Connaissance" },
            { q: "vivre", a: "vivir", m: "Identique.", cat: "Vie" },
            { q: "croire", a: "creer", m: "Croire en ce qu'on crée.", cat: "Pensée" },
            { q: "parler", a: "hablar", m: "Bla bla.", cat: "Communication" },
            { q: "aimer", a: "amar", m: "Amour.", cat: "Désir" },
            { q: "passer", a: "pasar", m: "Passage.", cat: "Actions" },
            { q: "laisser", a: "dejar", m: "Déjà laissé.", cat: "Actions" },
            { q: "rester", a: "quedar", m: "Rester sur le quai.", cat: "Déplacement" },
            { q: "trouver", a: "encontrar", m: "Trouver un trou.", cat: "Perception" },
            { q: "appeler", a: "llamar", m: "Appeler à la mer.", cat: "Communication" },
            { q: "penser", a: "pensar", m: "Identique.", cat: "Pensée" },
            { q: "comprendre", a: "entender", m: "Tendre l'oreille.", cat: "Pensée" },
            { q: "sembler", a: "parecer", m: "Paraître.", cat: "Perception" },
            { q: "manquer", a: "faltar", m: "Une faute.", cat: "Actions" },
            { q: "attendre / espérer", a: "esperar", m: "Espérer en attendant.", cat: "Pensée" },
            { q: "demander", a: "pedir", m: "Pitié.", cat: "Communication" },
            { q: "répondre", a: "responder", m: "Identique.", cat: "Communication" },
            { q: "perdre", a: "perder", m: "Identique.", cat: "Actions" },
            { q: "ouvrir", a: "abrir", m: "En avril on ouvre.", cat: "Actions" },
            { q: "fermer", a: "cerrar", m: "Serrer pour fermer.", cat: "Actions" },
            { q: "écouter", a: "escuchar", m: "Écoute.", cat: "Perception" },
            { q: "lire", a: "leer", m: "Identique.", cat: "Loisirs" },
            { q: "écrire", a: "escribir", m: "Écrire en criant.", cat: "Communication" },
            { q: "boire", a: "beber", m: "Biberon.", cat: "Besoins" },
            { q: "manger", a: "comer", m: "Comestible.", cat: "Besoins" },
            { q: "dormir", a: "dormir", m: "Identique.", cat: "Besoins" },
            { q: "arriver", a: "llegar", m: "Arriver léger.", cat: "Déplacement" },
            { q: "partager", a: "compartir", m: "Partager une part.", cat: "Social" },
            { q: "jouer", a: "jugar", m: "Jeu.", cat: "Loisirs" },
            { q: "acheter", a: "comprar", m: "Compter pour acheter.", cat: "Actions" },
            { q: "vendre", a: "vender", m: "Identique.", cat: "Actions" },
            { q: "travailler", a: "trabajar", m: "Identique.", cat: "Actions" },
            { q: "étudier", a: "estudiar", m: "Identique.", cat: "Loisirs" },
            { q: "regarder", a: "mirar", m: "Miroir.", cat: "Perception" },
            { q: "entendre", a: "oír", m: "Oh !", cat: "Perception" },
            { q: "sentir", a: "sentir", m: "Identique.", cat: "Perception" },
            { q: "toucher / jouer d'un instrument", a: "tocar", m: "Toc toc.", cat: "Perception" },
            { q: "chercher", a: "buscar", m: "chercher le bus.", cat: "Actions" },
            { q: "choisir", a: "elegir", m: "Elégant.", cat: "Actions" },
            { q: "porter", a: "llevar", m: "Lève le vêtement.", cat: "Actions" },
            { q: "gagner", a: "ganar", m: "Gain.", cat: "Actions" },
            { q: "commencer", a: "empezar", m: "Poisson (pez).", cat: "Actions" },
            { q: "finir", a: "terminar", m: "Terme.", cat: "Actions" },
            { q: "répéter", a: "repetir", m: "Identique.", cat: "Communication" },
            { q: "apprendre", a: "aprender", m: "Prendre connaissance.", cat: "Loisirs" },
            { q: "enseigner", a: "enseñar", m: "Signer.", cat: "Loisirs" },
            { q: "oublier", a: "olvidar", m: "oubli.", cat: "Pensée" },
            { q: "se souvenir", a: "recordar", m: "record.", cat: "Pensée" },
            { q: "lancer", a: "lanzar", m: "lance.", cat: "Actions" }
        ]
    }
];

const verbSpecialData = {
    fillIn: {
        infinitif: [
            { q: "¿Quieres [manger] ___ conmigo?", a: "comer" },
            { q: "Es importante [étudier] ___ todos los días.", a: "estudiar" },
            { q: "No puedo [dormir] ___ bien.", a: "dormir" },
            { q: "Me gusta [chanter] ___ en la ducha.", a: "cantar" },
            { q: "Voy a [vendre] ___ mi coche.", a: "vender" },
            { q: "Tenemos que [travailler] ___ mañana.", a: "trabajar" },
            { q: "Prefiero [lire] ___ un libro.", a: "leer" },
            { q: "¿Sabes [parler] ___ español?", a: "hablar" },
            { q: "Es difícil [comprendre] ___ todo.", a: "entender" },
            { q: "Tienes que [partager] ___ tu juguete.", a: "compartir" },
            { q: "Vamos a [acheter] ___ pan.", a: "comprar" },
            { q: "Debes [écouter] ___ al profesor.", a: "escuchar" },
            { q: "Quiero [apprendre] ___ a cocinar.", a: "aprender" },
            { q: "¿Vas a [sortir] ___ hoy?", a: "salir" },
            { q: "Intenté [donner] ___ un regalo.", a: "dar" },
            { q: "Ella quiere [connaître] ___ el mundo.", a: "conocer" },
            { q: "Necesito [prendre] ___ un café.", a: "tomar" },
            { q: "Empiezo a [écrire] ___ una carta.", a: "escribir" },
            { q: "Pienso [finir] ___ pronto.", a: "terminar" },
            { q: "Espero [voir] ___ a mis amigos.", a: "ver" }
        ],
        present: [
            { q: "Yo [parler] ___ español.", a: "hablo" },
            { q: "Ella [vivre] ___ en Madrid.", a: "vive" },
            { q: "Nosotros [manger] ___ juntos.", a: "comemos" },
            { q: "Tú [avoir] ___ un gato.", a: "tienes" },
            { q: "Ellos [être/ser] ___ inteligentes.", a: "son" },
            { q: "Ustedes [aller] ___ al cine.", a: "van" },
            { q: "Yo [pouvoir] ___ hacerlo.", a: "puedo" },
            { q: "Él [faire] ___ los deberes.", a: "hace" },
            { q: "Nosotros [vouloir] ___ agua.", a: "queremos" },
            { q: "Tú [boire] ___ leche.", a: "bebes" },
            { q: "Ella [travailler] ___ mucho.", a: "trabaja" },
            { q: "Yo [dire] ___ la verdad.", a: "digo" },
            { q: "Nosotros [aller/transport] ___ en tren.", a: "vamos" },
            { q: "Ellos [écouter] ___ música.", a: "escuchan" },
            { q: "Tú [écrire] ___ un libro.", a: "escribes" },
            { q: "Yo [donner] ___ las llaves.", a: "doy" },
            { q: "Ella [penser] ___ en ti.", a: "piensa" },
            { q: "Nosotros [jouer] ___ al fútbol.", a: "jugamos" },
            { q: "Tú [comprendre] ___ la lección.", a: "entiendes" },
            { q: "Yo [savoir] ___ nadar.", a: "sé" }
        ],
        imperatif: [
            { q: "[Parler] ___ más alto. (tú)", a: "Habla" },
            { q: "[Manger] ___ la sopa. (tú)", a: "Come" },
            { q: "[Ouvrir] ___ la ventana. (tú)", a: "Abre" },
            { q: "[Écouter] ___ con atención. (tú)", a: "Escucha" },
            { q: "[Fermer] ___ la puerta. (tú)", a: "Cierra" },
            { q: "[Faire] ___ la cama. (tú)", a: "Haz" },
            { q: "[Aller] ___ a casa. (tú)", a: "Ve" },
            { q: "[Dire] ___ hola. (tú)", a: "Di" },
            { q: "[Donner] ___ el dinero. (tú)", a: "Da" },
            { q: "[Mettre] ___ la mesa. (tú)", a: "Pon" },
            { q: "[Prendre] ___ el autobús. (tú)", a: "Toma" },
            { q: "[Sortir] ___ de aquí. (tú)", a: "Sal" },
            { q: "[Regarder] ___ el paisaje. (tú)", a: "Mira" },
            { q: "[Penser] ___ bien. (tú)", a: "Piensa" },
            { q: "[Écrire] ___ tu nombre. (tú)", a: "Escribe" },
            { q: "[Lire] ___ el texto. (tú)", a: "Lee" },
            { q: "[Dormir] ___ un poco. (tú)", a: "Duerme" },
            { q: "[Chercher] ___ las llaves. (tú)", a: "Busca" },
            { q: "[Étudier] ___ para el examen. (tú)", a: "Estudia" },
            { q: "[Chanter] ___ una canción. (tú)", a: "Canta" }
        ]
    },
    methods: [
        {
            title: "L'Infinitif",
            content: "L'infinitif est la forme non conjuguée du verbe. En espagnol, il existe trois groupes de verbes se terminant par : <br>1. <strong>-AR</strong> (ex: Hablar)<br>2. <strong>-ER</strong> (ex: Comer)<br>3. <strong>-IR</strong> (ex: Vivir).<br><br>Utilisation : Après une préposition (para comer), ou un verbe d'envie/obligation (Quiero estudiar, Debo salir)."
        },
        {
            title: "Le Présent",
            content: "Le présent de l'indicatif s'utilise pour des actions habituelles ou actuelles.<br><br><strong>Terminaisons régulières :</strong><br>-AR : -o, -as, -a, -amos, -áis, -an<br>-ER : -o, -es, -e, -emos, -éis, -en<br>-IR : -o, -es, -e, -imos, -ís, -en<br><br>Attention aux irréguliers comme <strong>Ser</strong> (Soy), <strong>IR</strong> (Voy) ou les verbes à diphtongue (Poder -> Puedo)."
        },
        {
            title: "L'Impératif (tú)",
            content: "L'impératif s'utilise pour donner des ordres, des conseils ou faire des demandes.<br><br><strong>Formation (Affirmatif tú régulier) :</strong><br>- Verbes en -AR : Enlève le -s de la 2ème pers. du présent (Hablas -> <strong>Habla</strong>)<br>- Verbes en -ER/-IR : Enlève le -s de la 2ème pers. du présent (Comes -> <strong>Come</strong>, Abres -> <strong>Abre</strong>)<br><br><strong>Irréguliers célèbres :</strong> Ven, Di, Sal, Haz, Ten, Ve, Pon, Sé."
        }
    ]
};
