// Pre-processed data for the A1 Spanish Quiz App
const themesData = [
    {
        id: "food",
        nameFr: "Nourriture / boissons / restaurant",
        nameEs: "Alimentación y Restaurante",
        icon: "🍴",
        color: "#FF6B6B",
        questions: [
            { q: "pomme", a: "manzana", m: "Imagine une pomme qui chante 'manzana' en dansant.", cat: "Fruits" },
            { q: "poire", a: "pera", m: "Pense à 'Père Noël' qui mange une 'pera' à Noël.", cat: "Fruits" },
            { q: "pêche", a: "melocotón", m: "'Melocotón' contient 'melo' comme dans 'melodie' : une pêche mélodieuse.", cat: "Fruits" },
            { q: "orange", a: "naranja", m: "'Naranja' rime avec 'orange' et contient 'naran' comme 'narrateur' : une orange qui raconte des histoires.", cat: "Fruits" },
            { q: "pastèque", a: "sandía", m: "'Sandía' contient 'sand' comme 'sable' : une pastèque sur la plage.", cat: "Fruits" },
            { q: "mûre", a: "mora", m: "'Mora' ressemble à 'mure' en français, imagine une muraille de mûres.", cat: "Fruits" },
            { q: "fraise", a: "fresa", m: "'Fresa' ressemble à 'fraise' et contient 'fres' comme 'frais'.", cat: "Fruits" },
            { q: "cerise", a: "cereza", m: "'Cereza' contient 'cere' comme dans 'céréale'.", cat: "Fruits" },
            { q: "citron", a: "limón", m: "'Limón' ressemble à 'limonade', qui est faite avec du citron.", cat: "Fruits" },
            { q: "melon", a: "melón", m: "Le mot est presque identique en français et en espagnol.", cat: "Fruits" },
            { q: "myrtille", a: "arándano", m: "'Arándano' contient 'rano' comme dans 'grenouille' (rana), imagine une grenouille bleue qui mange des myrtilles.", cat: "Fruits" },
            { q: "raisin", a: "uva", m: "'Uva' est court et facile : imagine une grappe de raisin en forme de 'U'.", cat: "Fruits" },
            { q: "ananas", a: "piña", m: "'Piña' ressemble à 'pine', comme l'ananas qui a des feuilles pointues comme un pin.", cat: "Fruits" },
            { q: "banane", a: "plátano", m: "'Plátano' contient 'plat' : imagine une banane plate.", cat: "Fruits" },
            { q: "mangue", a: "mango", m: "Le mot est identique en français et en espagnol.", cat: "Fruits" },
            { q: "kiwi", a: "kiwi", m: "Le mot est identique en français et en espagnol.", cat: "Fruits" },
            { q: "avocat", a: "aguacate", m: "'Aguacate' contient 'agua' (eau) et 'cate' comme dans 'catapulte' : un avocat qui catapulte de l'eau.", cat: "Fruits" },
            { q: "prune", a: "ciruela", m: "'Ciruela' contient 'cir' comme dans 'cirque' : une prune qui fait le cirque.", cat: "Fruits" },
            { q: "pain", a: "pan", m: "'Pan' est très proche du mot français, imagine un panier à pain.", cat: "Boulangerie" },
            { q: "vin", a: "vino", m: "'Vino' ressemble à 'vin ô' : un vin qui dit 'oh'.", cat: "Boissons" },
            { q: "soupe", a: "sopa", m: "'Sopa' ressemble à 'soupe' et contient 'opa' comme dans 'opéra' : une soupe qui chante à l'opéra.", cat: "Plats" },
            { q: "thé", a: "té", m: "Le mot est identique en français et en espagnol.", cat: "Boissons" },
            { q: "sandwich", a: "sándwich", m: "Le mot est presque identique en français et en espagnol.", cat: "Plats" },
            { q: "eau", a: "agua", m: "'Agua' ressemble à 'eau' et commence par 'a' comme 'aquatique'.", cat: "Boissons" },
            { q: "saumon", a: "salmón", m: "'Salmón' contient 'sal' comme dans 'saleté' : un saumon qui nage dans la mer salée.", cat: "Poisson" },
            { q: "salade", a: "ensalada", m: "'Ensalada' contient 'salade' : pense à 'en salade'.", cat: "Plats" },
            { q: "poulet", a: "pollo", m: "'Pollo' ressemble à 'poulet' et contient 'polo', comme un poulet qui joue au polo.", cat: "Viande" },
            { q: "bœuf", a: "carne", m: "'Carne' signifie 'viande' en général, pense à 'carnivore'.", cat: "Viande" },
            { q: "noix", a: "nuez", m: "'Nuez' ressemble à 'nœud' : une noix qui fait un nœud dans un arbre.", cat: "Encas" },
            { q: "cacahuète", a: "cacahuete", m: "Le mot est identique en français et en espagnol.", cat: "Encas" },
            { q: "amande", a: "almendra", m: "'Almendra' contient 'amande' et 'al' comme dans 'allumette' : une amande en forme d'allumette.", cat: "Encas" },
            { q: "chou", a: "repollo", m: "'Repollo' contient 'pollo' comme 'poulet' : un chou qui ressemble à un poulet.", cat: "Légumes" },
            { q: "maïs", a: "maíz", m: "'Maíz' contient 'maïs' et se termine par 'z' comme 'zèbre' : un champ de maïs avec des zèbres.", cat: "Légumes" },
            { q: "haricot", a: "frijol", m: "'Frijol' contient 'fri' comme dans 'frit' : un haricot frit.", cat: "Légumes" },
            { q: "pois", a: "guisante", m: "'Guisante' contient 'guise' comme dans 'déguisement' : un pois déguisé.", cat: "Légumes" },
            { q: "brocoli", a: "brócoli", m: "Le mot est presque identique en français et en espagnol.", cat: "Légumes" },
            { q: "carotte", a: "zanahoria", m: "'Zanahoria' contient 'zani' comme dans 'zany' (farfelu) : une carotte farfelue.", cat: "Légumes" },
            { q: "poivron", a: "pimiento", m: "'Pimiento' contient 'piment' : un poivron qui pimente.", cat: "Légumes" },
            { q: "piment", a: "chile", m: "'Chile' comme le pays, imagine un piment en forme de Chili.", cat: "Légumes" },
            { q: "citrouille", a: "calabaza", m: "'Calabaza' contient 'cal' comme dans 'calcul' : une citrouille qui calcule.", cat: "Légumes" },
            { q: "aubergine", a: "berenjena", m: "'Berenjena' contient 'bère' comme dans 'berceuse' : une aubergine qui berce.", cat: "Légumes" },
            { q: "oignon", a: "cebolla", m: "'Cebolla' contient 'bola' (balle) : un oignon en forme de balle.", cat: "Légumes" },
            { q: "ail", a: "ajo", m: "'Ajo' est court et facile, pense à 'ail ô' : un ail qui dit 'oh'.", cat: "Légumes" },
            { q: "dinde", a: "pavo", m: "'Pavo' ressemble à 'pava' comme dans 'pavane' : une dinde qui danse la pavane.", cat: "Viande" },
            { q: "riz", a: "arroz", m: "'Arroz' contient 'roz' comme dans 'rose' : du riz en forme de roses.", cat: "Plats" },
            { q: "steak", a: "filete", m: "'Filete' contient 'filet' : un steak en filet.", cat: "Viande" },
            { q: "crevette", a: "gamba", m: "'Gamba' ressemble à 'jambe' : une crevette avec des jambes.", cat: "Poisson" },
            { q: "fromage", a: "queso", m: "'Queso' ressemble à 'késako' : un fromage mystérieux.", cat: "Produits laitiers" },
            { q: "œuf", a: "huevo", m: "'Huevo' commence par 'hue', comme 'huer' (crier) : un œuf qui crie.", cat: "Base" },
            { q: "pâtes", a: "pasta", m: "Le mot est presque identique en français et en espagnol.", cat: "Plats" },
            { q: "pizza", a: "pizza", m: "Le mot est identique en français et en espagnol.", cat: "Plats" },
            { q: "hamburger", a: "hamburguesa", m: "'Hamburguesa' contient 'hamburger' : facile à retenir.", cat: "Plats" },
            { q: "hot-dog", a: "perro caliente", m: "'Perro caliente' signifie 'chien chaud' : un hot-dog en forme de chien.", cat: "Plats" },
            { q: "café", a: "café", m: "Le mot est identique en français et en espagnol.", cat: "Boissons" },
            { q: "bière", a: "cerveza", m: "'Cerveza' contient 'cerve' comme dans 'cerveau' : une bière qui donne des idées.", cat: "Boissons" },
            { q: "champagne", a: "champán", m: "'Champán' ressemble à 'champagne' et se termine par 'án' comme 'année' : du champagne pour la nouvelle année.", cat: "Boissons" },
            { q: "soda", a: "refresco", m: "'Refresco' contient 'frais' : un soda rafraîchissant.", cat: "Boissons" }
        ]
    },
    {
        id: "city",
        nameFr: "Ville / maison / lieux / transport",
        nameEs: "Ciudad, Casa y Transporte",
        icon: "🏙️",
        color: "#4D96FF",
        questions: [
            { q: "la ville", a: "la ciudad", m: "Pense à 'city' en anglais, qui ressemble à 'ciudad'.", cat: "Ville" },
            { q: "la rue", a: "la calle", m: "Imagine-toi en train de 'caller' (appeler) quelqu’un dans la rue.", cat: "Ville" },
            { q: "la place", a: "la plaza", m: "Pense à la 'Piazza' en italien, qui ressemble à 'plaza'.", cat: "Ville" },
            { q: "le parc", a: "el parque", m: "Le mot 'parque' ressemble au français 'parc'.", cat: "Lieux" },
            { q: "le magasin", a: "la tienda", m: "Pense à 'tente' : une boutique peut ressembler à une tente sur un marché.", cat: "Commerce" },
            { q: "le restaurant", a: "el restaurante", m: "Le mot se termine comme 'restaurant' en français.", cat: "Commerce" },
            { q: "la maison", a: "la casa", m: "Pense à la 'casa' de 'casanova'.", cat: "Habitation" },
            { q: "l’école", a: "la escuela", m: "Le mot contient 'cole', comme 'collège' en français.", cat: "Lieux" },
            { q: "l’hôpital", a: "el hospital", m: "Le mot ressemble à 'hospital' en anglais.", cat: "Santé" },
            { q: "le musée", a: "el museo", m: "Le mot est presque identique au français 'musée'.", cat: "Loisirs" },
            { q: "le cinéma", a: "el cine", m: "Pense à 'cinéma' sans le 'ma' final.", cat: "Loisirs" },
            { q: "la banque", a: "el banco", m: "Pense à 'banque' et à 'banc' (siège), car on peut s’asseoir devant une banque.", cat: "Lieux" },
            { q: "la gare", a: "la estación", m: "Pense à 'station' en français, car une gare est une station de train.", cat: "Transport" },
            { q: "le métro", a: "el metro", m: "Le mot est identique en français et en espagnol.", cat: "Transport" },
            { q: "le bus", a: "el autobús", m: "Pense à 'auto' (voiture) et 'bus'.", cat: "Transport" },
            { q: "le taxi", a: "el taxi", m: "Le mot est identique en français et en espagnol.", cat: "Transport" },
            { q: "la voiture", a: "el coche", m: "Pense à 'cocher' : on peut cocher une case pour réserver une voiture.", cat: "Transport" },
            { q: "le vélo", a: "la bicicleta", m: "Pense à 'bicyclette' en français.", cat: "Transport" },
            { q: "le salon", a: "el salón", m: "Pensez à un salon élégant où l'on reçoit les invités.", cat: "Maison" },
            { q: "la cuisine", a: "la cocina", m: "Imaginez-vous en train de cuisiner des plats délicieux.", cat: "Maison" },
            { q: "la chambre", a: "el dormitorio", m: "C'est là où l'on dort, 'dormitorio' vient de dormir.", cat: "Maison" },
            { q: "le lit", a: "la cama", m: "C'est là où l'on dort, comme en français.", cat: "Mobilier" },
            { q: "le canapé", a: "el sofá", m: "Le mot est identique au français.", cat: "Mobilier" }
        ]
    },
    {
        id: "activities",
        nameFr: "Activités / sports",
        nameEs: "Actividades y Deportes",
        icon: "⚽",
        color: "#6BCB77",
        questions: [
            { q: "courir", a: "correr", m: "'Correr' et 'courir' commencent tous les deux par 'cor-'.", cat: "Verbes" },
            { q: "marcher", a: "caminar", m: "'Caminar' et 'marcher' ont tous deux un 'm' et un 'r'.", cat: "Verbes" },
            { q: "écrire", a: "escribir", m: "'Escribir' et 'écrire' commencent par un 'e'.", cat: "Verbes" },
            { q: "boire", a: "beber", m: "'Beber' et 'boire' commencent tous deux par un 'b'.", cat: "Verbes" },
            { q: "travailler", a: "trabajar", m: "'Trabajar' et 'travailler' commencent par 'tra-'.", cat: "Verbes" },
            { q: "lire", a: "leer", m: "'Leer' et 'lire' commencent tous deux par un 'l'.", cat: "Verbes" },
            { q: "manger", a: "comer", m: "L'action de se nourrir.", cat: "Verbes" },
            { q: "natation", a: "natación", m: "Ressemble au français 'natation'.", cat: "Sports" },
            { q: "escrime", a: "esgrima", m: "L'arme s'appelle un 'escrime'.", cat: "Sports" },
            { q: "basket-ball", a: "baloncesto", m: "Pensez au 'ballon' dans le 'cesto' (panier).", cat: "Sports" },
            { q: "tennis", a: "tenis", m: "Presque identique.", cat: "Sports" },
            { q: "athlétisme", a: "atletismo", m: "Très proche du français.", cat: "Sports" },
            { q: "boxe", a: "boxeo", m: "Ajoutez un 'o' à boxe.", cat: "Sports" },
            { q: "football", a: "fútbol", m: "L'accent est sur le 'ú'.", cat: "Sports" },
            { q: "nager", a: "nadar", m: "Nageur, nager, nadar.", cat: "Verbes" },
            { q: "danser", a: "bailar", m: "Bailar, comme un bal.", cat: "Verbes" },
            { q: "chanter", a: "cantar", m: "Comme une cantate.", cat: "Verbes" }
        ]
    },
    {
        id: "environment",
        nameFr: "L'environnement / planète",
        nameEs: "Medio Ambiente y Planeta",
        icon: "🌍",
        color: "#47B5FF",
        questions: [
            { q: "environnement", a: "medio ambiente", m: "Imaginez un 'médium' qui parle de l'environnement.", cat: "Général" },
            { q: "recyclage", a: "reciclaje", m: "Pensez à 'cycle' dans 'reciclaje'.", cat: "Action" },
            { q: "énergie solaire", a: "energía solar", m: "Pensez au soleil (sol).", cat: "Énergie" },
            { q: "déforestation", a: "deforestación", m: "Pensez à 'forêt'.", cat: "Problèmes" },
            { q: "pollution", a: "contaminación", m: "Imaginez un conteneur contaminé.", cat: "Problèmes" },
            { q: "planète", a: "planeta", m: "Très proche du français.", cat: "Général" },
            { q: "nature", a: "naturaleza", m: "C'est la nature.", cat: "Général" },
            { q: "réchauffement climatique", a: "calentamiento global", m: "Calentamiento vient de 'caliente' (chaud).", cat: "Problèmes" }
        ]
    },
    {
        id: "health",
        nameFr: "La santé / corps humains",
        nameEs: "Salud y Cuerpo Humano",
        icon: "🏥",
        color: "#D67BFF",
        questions: [
            { q: "tête", a: "cabeza", m: "Pensez à 'caboche'.", cat: "Corps" },
            { q: "bras", a: "brazo", m: "Ressemble au bras.", cat: "Corps" },
            { q: "main", a: "mano", m: "Une manœuvre se fait à la main.", cat: "Corps" },
            { q: "jambe", a: "pierna", m: "On se tient sur ses jambes.", cat: "Corps" },
            { q: "pied", a: "pie", m: "Un pied.", cat: "Corps" },
            { q: "œil", a: "ojo", m: "Les yeux sont le miroir de l'âme.", cat: "Corps" },
            { q: "nez", a: "nariz", m: "Les narines.", cat: "Corps" },
            { q: "bouche", a: "boca", m: "La bouche.", cat: "Corps" },
            { q: "malade", a: "enfermo", m: "Enfermo ressemble à l'enfer.", cat: "Santé" },
            { q: "médecin", a: "médico", m: "On y ajoute un 'o'.", cat: "Santé" },
            { q: "pharmacie", a: "farmacia", m: "Ressemble à farmacia.", cat: "Santé" },
            { q: "hôpital", a: "hospital", m: "Identique sans l'accent.", cat: "Santé" }
        ]
    }
];
